### ISSUE TITLE
Algumas Configurações Iniciais Theme

### ISSUE THREAD

**Issue by enniolopes** [ttoss/dev-school#5]

**Comment by enniolopes** [comment]
Usei esse framework de ícones, achei fácil usar e é o mesmo que uso no Figma.

https://iconify.design/

**Comment by arantespp** [comment]
> Usei esse framework de ícones, achei fácil usar e é o mesmo que uso no Figma.
> 
> https://iconify.design/

Perfeito. Inclusive podemos usar em todos os nossos outros projetos.
